biglotteryfund/craft-dev

composer.json
composer.lock

Uses https://github.com/borucreative/craft3-ses

Install SES mail transport

---

config/element-api.php

This change does two things:
- Switches API methods to use the JSON-API serializer (http://jsonapi.org/)
- Updates API endpoints to support creating breaking changes without removing existing endpoints (to help in gradual rollouts)
This second points warrants discussion as I'm still not completely sold on the versioning naming scheme 💭

Update API endpoints and enable jsonapi serializer

---

config/element-api.php

Remove old funding-programmes endpoint

---

config/element-api.php
translations/cy/site.php
translations/en/site.php

Localises the region names using translation files. 🌐

Add global translations

---

config/element-api.php
translations/cy/site.php
translations/en/site.php

Expose the content linkUrl field in addition to the underlying craft url.

Translations

---

config/element-api.php

Fix funding detail route

---

config/element-api.php

Ensure opening slash is appended to uri for linkUrl

Ensure opening slash is appended to uri for linkUrl

---

config/redactor/Standard.json

Limit formatting options to h2-h5.

Limit formatting options to h2-h5

---

config/element-api.php

Return the welsh version of the path URL if requested in cy locale. We already support the URLs on the app end, but I wasn't returning it from the API yet.

Output welsh path URL if in cy locale

---

config/element-api.php
config/redactor/Standard.json

This adds an endpoint to return the (currently very basic) content for a legacy page.

Legacy pages

---

config/element-api.php

Add an endpoint for this "listing" structure.
Down the line we may wish to make this more generic for other, similar structures.

Funding guidance

---

config/element-api.php

This allows us to output a hero image (if set) for a funding programme.

Add hero images to API

---

composer.json
composer.lock

Upgrade Craft to RC-4

---

composer.json
composer.lock
config/general.php

Update to RC-5, fix deprecation warning

Update to RC-5, fix deprecation warning

---

config/element-api.php

Return 404 if `useNewContent` is not set on programme detail endpoint.

Return 404 if useNewContent is not set

---

composer.json
composer.lock

Craft upgrade

---

config/element-api.php

Add hero images to content pages, extract method to share between API endpoints.

Add hero images to content pages, extract method

---

config/htmlpurifier/safe-iframe-media.json

Allow embeds from google (e.g. google maps)

Allow embeds from google (e.g. google maps)

---

composer.json
composer.lock

Add Field Manager plugin

---

composer.json
composer.lock

Not wild on getting completely wedded to plugins for core content, but looks useful so worth an explore the next time we build out a section. https://github.com/verbb/super-table

Add super-table

---

config/element-api.php

API endpoint for https://github.com/biglotteryfund/blf-alpha/pull/680

Expose list-routes endpoint to get all active routes

---

config/element-api.php

Add case studies to listing endpoint and clean up file structure / add some comments.

Case studies

---

config/element-api.php

This lets us retrieve surveys (optionally with a `all` flag to get expired ones) to display on the site.

Add surveys

---

config/element-api.php

Adds another database query, but not sure there's a way to do this with the element API without it. Adds an array of available languages:

Add available languages to funding programmes

---

config/element-api.php

Simplify `getAvailableLanguages` so it requires fewer arguments, add to listing endpoint

Simplify getAvailableLanguages, add to listing endpoint

---

config/element-api.php

Add profiles endpoint. Takes a section name so it can be reused for different sections (e.g. senior management or board members).

Add profiles endpoint

---

snapshots/fields.json

Commits an export snapshot of all fields that are currently on the live site.

Commit fields snapshot

---

composer.json
composer.lock
config/element-api.php

Fixes a couple of bugs:
- Revert back to RC13, drafts broken, fixed in next RC (https://github.com/craftcms/cms/issues/2544)
- Fixes an issue where `useNewContent` was checked before fetching draft preventing preview working for new programme pages.

Draft programmes

---

config/element-api.php

Add case-studies endpoint which lists all case studies.

Add case-studies endpoint

---

config/element-api.php
lib/EntryHelpers.php

Extract more helpers into `EntryHelpers`

Extract helpers

---

composer.json
composer.lock
lib/Images.php

Got a PR merged in the Imgix PHP library so we can avoid using the full constructor.
https://github.com/imgix/imgix-php/pull/32

Update imgix-php to latest version

---

config/element-api.php

Use custom thumbnail if one is set, otherwise default to hero image.

Use custom thumbnail if one is set, otherwise default to hero image

---

lib/Images.php

Reverting this because I'm a little cart before the horse. Need to make some config changes first.

Revert "Updates Imgix config to use signed urls"

---

lib/Images.php

This reverts commit d0e85cd3a4d2c8254dad9a5099f584ae5fb0edd8.

Revert "Revert "Updates Imgix config to use signed urls""

---

.travis.yml
composer.json
composer.lock
tests/ImagesTest.php
tests/bootstrap.php

This is more to make sure it's possible to write unit tests for the new helper functions, rather than an ambition to have full coverage. I'm still erring towards the separate HTTP tests as being a more straightforward way of testing this stuff.

Add initial basic phpunit test

---

config/element-api.php
lib/EntryHelpers.php
lib/Images.php

A few tweaks prompted by https://github.com/biglotteryfund/api-tests/pull/3

API tweaks

---

composer.json
composer.lock

Looks like Craft 3.0 has been released now, so let's update to this.

Update to Craft 3 public release

---

config/element-api.php

Add endpoint to return aliases defined in the CMS

Add endpoint to return aliases

---

composer.lock

Update Craft to 3.0.7

---

config/element-api.php

Allows us to represent free merchandise products in the CMS.

Add materials/merch to the CMS API

---

config/element-api.php
lib/EntryHelpers.php

See https://github.com/biglotteryfund/blf-alpha/pull/997

Add new flexible content endpoint

---

lib/BlogPosts.php
lib/EntryHelpers.php

Pairs with https://github.com/biglotteryfund/blf-alpha/pull/998

Update blog posts to use new flexible content

---

README.md
composer.lock
config/general.php

- Upgrade Craft to 3.10
- Disable transforms for animated gifs

Craft updates

---

config/element-api.php

We're not calling this anymore so we can probably remove this.

Remove deprecated surveys endpoint

---

config/element-api.php
lib/FundingProgrammes.php
lib/Images.php

See https://github.com/biglotteryfund/blf-alpha/pull/1096

Extract funding programme transformer and add heroCredit field

---

lib/StrategicProgrammes.php

Add cropped partner logo to API response

Add cropped partner logo

---

composer.json
composer.lock
config/element-api.php
lib/ContentHelpers.php
lib/EntryHelpers.php
lib/Research.php
lib/StringHelpers.php
tests/StringHelpersTest.php

Adds endpoints for new research pages. Requires the `super-table` plugin for matrix within matrix fields. Also starts a little work to share some of the preview logic a bit more to avoid so much boilerplate.

Research API endpoints

---

config/element-api.php

Fix deprecation warning

---

config/element-api.php
lib/ContentHelpers.php
lib/EntryHelpers.php
lib/Images.php
lib/People.php

Reworks the our people section to be powered by a dedicated structure rather than individual channels profiles. Allows us to migrate the whole our people section.

Add our people endpoint

---

lib/FundingProgrammes.php

For AFA Scotland (see https://github.com/biglotteryfund/blf-alpha/issues/585)

Add footer field to API

---

config/element-api.php

Caught me out when debugging, increases the default page-limit at the API end to 10.

Increase default page limit

---

config/element-api.php

Remove unused stat-blocks endpoint

---

config/element-api.php

Remove old stat-regions endpoint 🗑

Remove old stat-regions endpoint

---

config/element-api.php
lib/ContentHelpers.php
lib/EntryHelpers.php
lib/FundingProgrammes.php
lib/Listing.php
lib/People.php
lib/Research.php
lib/StrategicProgrammes.php
lib/Updates.php

Merged my here image changes into the wrong branch…

New programmes api tweaks

---

config/element-api.php

Ensure we fetch localised tags (author, category, tag, region)

---

config/element-api.php
lib/ContentHelpers.php
lib/FundingProgrammes.php
lib/Homepage.php
lib/Images.php

- Removes unused promoted news endpoint (now powered by updates endpoint)
- Refactors `Images` helper methods
- Moves homepage code into `HomepageTransformer`
- Adds new and existing trail images for funding programmes

Api updates

---

config/element-api.php
lib/ContentHelpers.php
lib/FundingProgrammes.php
lib/Listing.php

Remove case studies in favour of project stories
Dependant on https://github.com/biglotteryfund/blf-alpha/pull/1629

Remove case studies in favour of project stories

---

composer.json
composer.lock

Not urgent but a few useful plugins:
eg. allows us to add those first two widgets, showing updated content instead of brand new.
eg. this is for NLAFA England – shows all the places linking to it and vice-versa. Particularly handy for hero images:

Add a couple of plugins

---

config/general.php
config/project.yaml
storage/config-backups/.gitignore

Adds a basic project config setup now the sensitive credentials have been moved to a .env file

Add initial project config

---

.ebextensions/craftlicense.config
.travis.yml
composer.json
composer.lock
config/general.php
config/project.yaml
storage/config-backups/.gitignore
templates/homepage/_entry.twig

Upgrade Craft to 3.1 and configure new project config file.

Upgrade Craft to 3.1

---

.travis.yml

Removes `upgrade` branch deploy

Update travis config to deploy to green environment

---

config/element-api.php
config/project.yaml
lib/ContentHelpers.php
lib/FundingProgrammes.php
lib/Images.php
lib/Listing.php
lib/ProjectStories.php
lib/Research.php
lib/StrategicProgrammes.php
lib/Updates.php

Reverts biglotteryfund/craft-dev#150

Revert "Field cleanup"

---

composer.lock
config/project.yaml

Update to craft 3.1.12

---

config/element-api.php
config/project.yaml
lib/ContentHelpers.php
lib/FundingProgrammes.php
lib/Images.php
lib/Listing.php
lib/ProjectStories.php
lib/Research.php
lib/StrategicProgrammes.php
lib/Updates.php

Field cleanup redo

---

config/element-api.php
config/project.yaml
lib/ContentHelpers.php
lib/FundingProgrammes.php
lib/Images.php
lib/Listing.php
lib/ProjectStories.php
lib/Research.php
lib/StrategicProgrammes.php
lib/Updates.php

Reverts biglotteryfund/craft-dev#155

Revert "Field cleanup redo"

---

config/htmlpurifier/safe-iframe-media.json

This came up today – the ability to embed Facebook videos would be useful (and perhaps tweets too).

Allow iframes from Facebook or Twitter

---

composer.lock
config/element-api.php
config/project.yaml
lib/ContentHelpers.php

The other PR ended up with some weird migration issues so I've restarted it using Matrix fields instead of `super-table` (which seems to be experiencing a few issues with [project config](https://github.com/verbb/super-table/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+project+config) anyway).
I upgraded some dependencies here too (possibly superseding https://github.com/biglotteryfund/craft-dev/pull/158?) initially in order to fix `super-table` issues but I guess it's also good hygiene too.
Confirmed this works as expected after a quick change to https://github.com/biglotteryfund/blf-alpha/pull/1821

Another stab at adding Open Graph tags

---

composer.json
composer.lock
config/project.yaml
config/redactor/Full.json
web/resources/css/cp.css

Allows us to wrap text around images in Redactor fields.

Allow Redactor to set classes for image alignment

---

config/project.yaml

To allow a new News section to launch.

Rename Updates content type to People Stories

---

config/htmlpurifier/safe-iframe-media.json

For a new podcast Engagement want to embed.

Allow Soundcloud embeds

---

lib/ContentHelpers.php

Bit of a niche bug, but:
If you set up social media metadata for an entry, the app will just grab the value of whatever the first item is as the "default" metadata, even if that item has a custom `?social=<slug>` setting, which should only be visible when accessed with the accompanying parameter. 
This changes means the default metadata (eg. no `social` slug) can be anywhere in the matrix array, it doesn't have to come first.

Allow blank social slugs to be anywhere in the list, not just first

---

README.md
docs/getting-started.md

Getting started read me file, will need the actual readme to be updated to include a link to this doc.

Getting started read me file for setup for new users.

---

config/project.yaml

Hero image field removed from the homepage section, which in turn; removes all existing hero images on the homepage.

Hero image field removed from homepage section as it is no longer used.

---

config/project.yaml

Removed the word new from both name and instruction fields for the hero image.

Removed references to new on hero image for name and instruction fields.

---

config/project.yaml

Removed the case studies section, its group, and all fields that it used:
grant amount, grant ID number, link URL, related case studies, thumbnail image, trail text, trail text more.
Tested loading the site and accessing project stories, all seems to be fine.

Removed case studies section

---

lib/ContentHelpers.php

Removed the 'heading' field and modified the code slightly to only declare $data where its used.

Removed redundant 'heading' field.

---

config/project.yaml
lib/Homepage.php

Allows FC to be added here too. Optional field.

Add Flexible Content to the homepage single entry

---

config/project.yaml
lib/ContentHelpers.php

Allows a last updated message to be shown above the table of contents. Defaults to false.

Add showLastUpdatedDate to table of contents block

---

config/project.yaml

Remove the Jobs, Big Lunch and Benefits sections, and remove the non-flexible content fields from About, Customer Service and BBO.

Delete unused sections and fields

---

config/element-api.php
config/project.yaml

Allows us to move some hard-coded data file releases into the CMS.

Add Flexible Content to /data page

---

config/element-api.php
config/project.yaml
lib/ContentHelpers.php
lib/ProjectStories.php
lib/Updates.php

Fixes https://github.com/biglotteryfund/blf-alpha/issues/3363 by pairing with https://github.com/biglotteryfund/blf-alpha/pull/3478
Also removes URLs from hero images as these don't exist and have never worked.

Rename flexiblecontent field consistently

---

.env.example
config/general.php
config/project.yaml

This change allows us to configure the TEST CMS instance to point to the TEST website.

Remove siteUrl in favour of explicitly specifying them in config

---

bin/get-secrets
composer.json
composer.lock
config/element-api.php
config/project.yaml

This will allow us to remove the (enormous) list of old URL redirects from the webapp, and handle the case where we rename content in the CMS and need to redirect to the new URLs. The Retour plugin will highlight unhandled 404s too which will allow us to create missing redirects where needed.

Install Retour plugin for redirects and add endpoint for querying

---

.travis.yml
config/project/entryTypes/grantmakingPractice--34dc3ee3-72ff-4906-a9df-4b2b94c9ad15.yaml
config/project/sections/grantmakingPractice--4526ec29-66b7-476d-92ca-712a962b38e8.yaml

Grantmaking practice section under insights

---

config/project/entryTypes/fundingProgrammes--79c88f21-da56-48db-9e1c-ec15618ca38f.yaml
config/project/fields/grantLengthDescription--889b8b45-4e52-4ecd-be0c-d1af48551bd9.yaml
config/project/fields/grantLengthMax--989964e9-8d01-487a-9709-76b6db1660bf.yaml
config/project/fields/grantLengthMin--d29df511-6b6a-4948-9d55-82ab34cd9b04.yaml
lib/FundingProgrammes.php

Created a new field for funding programme entry types for grant length and enabled the field for use on funding programmes

Grant length description field added

---

.travis.yml
README.md
composer.json
composer.lock
config/app.php
config/db.php
config/element-api.php
config/general.php
lib/biglotteryfund/Module.php
lib/biglotteryfund/conf/ConfigManager.php
lib/biglotteryfund/utils/ContentHelpers.php
lib/biglotteryfund/utils/EntryHelpers.php
lib/biglotteryfund/utils/FundingProgrammeTransformer.php
lib/biglotteryfund/utils/HomepageTransformer.php
lib/biglotteryfund/utils/Images.php
lib/biglotteryfund/utils/ListingTransformer.php
lib/biglotteryfund/utils/ProjectStoriesTransformer.php
lib/biglotteryfund/utils/ResearchDocumentTransformer.php
lib/biglotteryfund/utils/ResearchTransformer.php
lib/biglotteryfund/utils/StrategicProgrammeTransformer.php
lib/biglotteryfund/utils/StringHelpers.php
lib/biglotteryfund/utils/UpdatesTransformer.php
package.json
tests/ImagesTest.php
tests/StringHelpersTest.php

The code has been refactored to use Composer Version 2 and comply with PSR-4 standards.

Composer update to version 2

---

deploy/provision.sh

Updated the deployment files to use php 7.4

updated to php 7.4

---

craft

Added env function manually and reverted from getenv()

Env function manually added

---

craft

use $_ENV instead of env()

---

craft

using isset to prevent error in undefined index

using isset to prevent error in undefined index

---

deploy/start.sh

All commands now use sudo to ensure it works.

start.sh now uses sudo commands

---

deploy/start.sh

Enable debugging for start script to investigate issue.

enable debugging

---

deploy/start.sh

set e to terminate on failure

---

deploy/start.sh

diagnose start deployment failure

Diagnose start deployment failure

---

deploy/start.sh

fix error in command - remove dot when calling the file

fix error in command

---

.travis.yml
composer.lock
deploy/provision.sh
deploy/start.sh

Packages were updated during an update to composer v2. Reverted to fix pipeline.

Revert upgrades to all packages

---

appspec.yml
deploy/start.sh

- includes run as root for app start script
- start script logs stderr

Updated appspec

---

deploy/start.sh

Output stderr to log

---

.travis.yml
composer.lock
deploy/provision.sh

All packages updated to diagnose deployment failure.

package updates

---

.travis.yml
README.md
composer.json
composer.lock
config/app.php
config/db.php
config/element-api.php
config/general.php
lib/ConfigManager.php
lib/ContentHelpers.php
lib/EntryHelpers.php
lib/FundingProgrammes.php
lib/Homepage.php
lib/Images.php
lib/Listing.php
lib/ProjectStories.php
lib/Research.php
lib/ResearchDocument.php
lib/StrategicProgrammes.php
lib/StringHelpers.php
lib/Updates.php
modules/control-panel/Module.php
package.json
tests/ImagesTest.php
tests/StringHelpersTest.php

An alternative approach to complying with psr-4 that does not involve restructuring the files/renaming any. This should diagnose whether the deployment process failure is tied directly to an update to composer v2 or because of the change in the file structure.

Files updated to comply with psr-4

---

config/project/matrixBlockTypes/contentArea--0a6d79a3-0355-4217-a00b-8d5a416308f8.yaml

WEB-61 title no longer required on research entry types for the insights section

Insights research section title is no longer required

---

config/project/entryTypes/fundingProgrammes--79c88f21-da56-48db-9e1c-ec15618ca38f.yaml
config/project/project.yaml

In the settings, update the entry type to be translatable per site for the title.

WEB-79 update title to translatable per site

---

config/general.php

The functionality to access settings from the QA environment of the CMS.

WEB-81 Allow admin changes for qa env

---

config/project/matrixBlockTypes/contentArea--0a6d79a3-0355-4217-a00b-8d5a416308f8.yaml
config/project/matrixBlockTypes/lastUpdatedDateBlock--8659104e-f084-4a14-ae50-6293e9b7ea1d.yaml
lib/ContentHelpers.php

Created a new matrix field for flexible content that displays the last date the entry was updated

Last updated field added

---

config/project/matrixBlockTypes/alertBox--7b5e2e5f-35c6-417c-8e14-89c2c7a7d36c.yaml

This is a part of the flexible content field and is now an available option

Added alert box component

---

deploy/provision.sh

updated aws cli commands in provision.sh

updated aws cli commands in provision.sh
