biglotteryfund/craft-dev

config/element-api.php, translations/cy/site.php, translations/en/site.php
Much like the change to translate regions in https://github.com/biglotteryfund/craft-dev/pull/4 this PR translates the names of the organisation types. All other fields for funding programmes are text fields so can be translated through the CMS.
=> Adds translations for organisation types

composer.json, composer.lock, config/element-api.php, config/general.php
- Update Craft to beta.30
- Update element-api to 2.5
- Disables `allowAutoUpdates` as all this maps to behind the scenes is basically a `composer update` so it's much safer to run updates locally, commit and then deploy rather than having it happen through the UI
- Create a new `promoted-news` API endpoint to fetch promoted news
If the field modelling looks OK locally @mattandrews I'm probably going to take one more stab at writing an initial migration to add all the fields programatically based on the current local setup.
=> News models

config/element-api.php
Support optional funding size description. Used instead of the explicit range if provided.
=> Support optional funding size description

composer.json, composer.lock, config/cp-css.php, config/element-api.php, config/htmlpurifier/safe-iframe-media.json, web/custom/admin.css
- Upgrades to Craft 3 RC
- Adds Redactor as a plugin (moved to composer install)
- Adds an endpoint for fetching individual programmes
- Add `useNewContent` flag to programmes list endpoint to allow us to opt-in to new pages
=> Upgrade to Craft 3 RC and add programme API endpoint

config/element-api.php
I had this logic in the templates so moving `useNewContent` path logic into API. Makes `linkUrl` the single place to get the URL we should use in the templates. The [first commit](https://github.com/biglotteryfund/craft-dev/commit/69f0edcdfe09d0c0c70904b4f895b5ec627a9ee8) is the real change.
=> Path logic

config/element-api.php
Include expired entries in detail endpoint. Allows expiry date to be used to drop items off the listing, but still maintain the details page for historical purposes.
=> Support expired entries for detail endpoint

config/element-api.php
Stops filtering on section ID as we can accomplish this with just the URI path filter.
=> Remove hard-coded section path filter

composer.json, composer.lock
Remove SES plugin as:
- The plugin no longer works with Craft RC
- The plugin is not listed in the official plugins directory
- Amazon provide a direct SMTP transport so we can avoid using this plugin completely.
Test site reconfigured to use SMTP method.
=> Remove SES plugin in favour of using SMTP interface directly

config/element-api.php
We no longer call this endpoint from the express app, so we can remove the endpoint.
=> Remove legacy endpoint

composer.json, composer.lock, config/element-api.php, lib/EntryHelpers.php, lib/Images.php
This PR adds basic support for cropping and optimising images through Imgix.
Only set to run if `CUSTOM_IMGIX_DOMAIN` is set to we can merge this code before launching to production to test things out.
Two main changes:
- Funding programme thumbnail images are now created on the fly, so we can get rid of the custom thumbnail image field.
- Optimises hero images. Best case I could find was https://www.biglotteryfund.org.uk/funding/programmes/awards-from-the-uk-portfolio which is down from  **399KB** to **57KB** for the same quality images. Serves a compressed WebP image where available, otherwise falls back to jpg.
I've also made a start extracting helper methods out into separate classes so that `element-api.php` doesn't become a never ending file.
Rough, non-scientific, before and after …
=> Add support for Imgix images

lib/Images.php
This PR updates Imgix urls to use to a new source which points directly to S3 (using a single-purpose read-only key) and configured signed urls to prevent unwanted crops being generated. (see https://docs.imgix.com/setup/securing-images)
=> Updates Imgix config to use signed urls

composer.json, composer.lock, config/element-api.php, lib/EntryHelpers.php, lib/Images.php
Adds a new homepage API endpoint which allows homepage images to be managed via the CMS. They change with a reasonable enough frequency that this seems worthwhile.
Also aggregates the latest news into this same endpoint so the homepage can make a single request.
=> Add a new homepage API endpoint

config/element-api.php, lib/Images.php
- Adds a hero image endpoint, e.g. `api/v1/en/hero-image/image-slug`
- Extracts out a `buildHeroImage` function to share logic with existing hero image methods.
Companion for https://github.com/biglotteryfund/blf-alpha/pull/787
=> Add hero image endpoint

.ebextensions/craftlicense.config
This adds an Elastic Beanstalk script which fetches the Craft license key from S3, stores it in temporary folder (as the scope of the `files` script runs before the app is properly deployed), then when the app is ready to make live (the `container_commands` list), the license is copied to the correct place (eg. Craft's `/config` dir).
I've verified this is working on a test environment – I also think merging it shouldn't cause us issues as the Test CMS is already flagged as a non-live domain by Craft. Same should go for local environments too.
=> Add Craft license

.ebextensions/php.config
One of the PDF documents currently in the main app's `/files` directory is slightly larger than PHP's default 2mb limit. This PR should increase it.
=> Boost upload limit to 10MB (from default 2MB) for files

composer.lock, config/element-api.php, lib/EntryHelpers.php
This PR allows us to retrieve either listings of blogpost (grouped by category, content tag or author tag) or retrieve a single blogpost by slug.
URLs to try (using `TEST` CMS data):
- Author tag: `/api/v1/en/blog/author/montgomery-burns`
- Content tag: `/api/v1/en/blog/tag/hello-world`
- Blogpost: `/api/v1/en/blog/2018-04-26/purple-monkey-dishwasher`
- Category: `/api/v1/en/blog/funding-guidance`
- Subcategory: `/api/v1/en/blog/foo/bar`
=> Add support for fetching blogs

config/element-api.php
This is to aid migration of https://www.biglotteryfund.org.uk/data – stores the stats in the CMS:
I've made these categories rather than entries as I thought at one stage we might want to later associate these regions with things (eg. a dropdown field on an entry so we can associate news/programmes with a region). Could equally be a section, though.
=> Add some basic data/stat endpoints

config/element-api.php, lib/EntryHelpers.php
Welsh homepage is displaying English news: https://www.biglotteryfund.org.uk/welsh
This fix passes the `$locale` through so the news is in the correct language.
=> Pass the locale around when requesting homepage news

config/element-api.php, lib/EntryHelpers.php
It turns out there is a simpler way of approaching this https://github.com/biglotteryfund/craft-dev/pull/78 without the need for a big refactor and with fewer caveats.
When requested a draft or version we allow the 'disabled' status. This allows for new an unpublished entry to be previewed where the main entry is disabled and then a draft is created to preview the page.
=> Allow disabled entries when previewing

lib/ContentHelpers.php, lib/Research.php, tests/StringHelpersTest.php
Default precision of 2dp is more than we need on the front-end so updating out use to round the value:
will now appear as 824 KB
=> Use zero precision for estimated filesize

.travis.yml
I created a new user for Travis with new minimal permissions (via [this](https://gist.github.com/magnetikonline/5034bdbb049181a96ac9) gist). 
This reinstates auto-deploys to TEST from `master` commits (which is a bit redundant as that env isn't powering anything, but at least gives us somewhere to verify things haven't broken), and then a tag/release will deploy to PROD (like the new grants service). 
Thoughts welcome – if this looks okay then I'll make the same change to the Applications service.
Only potential issue is the hardcoded env name for `craft-production-blue` which we sometimes change, but can't think of a way around this for now.
=> Configure deploys to use Elastic Beanstalk for tags/master

config/element-api.php
As per @davidrapson's suggestion, this reworks the Data page stats so they're embedded in a Matrix field on a single page, eg:
The [corresponding PR](https://github.com/biglotteryfund/blf-alpha/pull/1270) for the website uses this new endpoint to power the Data page.
=> Add an endpoint for a single Data page

lib/EntryHelpers.php, lib/Images.php
Allows us to link a grant to a hero image or case study.
Down the line this could be a plugin which allows a lookup/search for the ID, but MVP and all that.
=> Add a basic grant ID field for heroes and case studies

config/cp-css.php
Supersedes https://github.com/biglotteryfund/craft-dev/pull/97
Removes a file we don't need anymore from an old plugin.
=> Remove unused cpcss file

config/element-api.php, lib/ContentHelpers.php, lib/People.php, lib/Research.php
Reworks the our people endpoint to:
- Provide more fields for the image to help us differentiate between large images and legacy thumbnail images
- Allow multiple groups of documents (e.g. to separate minutes and expenses) rather than a single group
=> Rework our people endpoint

config/element-api.php, lib/FundingProgrammes.php
This adds a field to the CMS called "programme status":
This allows us to distinguish between things that could be applied for directly (eg. now or in the past), and things that can't (eg. BBO). 
This then means we can pass `?all=true` to the programmes endpoint to get a list of expired programmes – eg. legacy programmes that aren't open to applicants anymore, but once were. This still excludes the strategic ones like BBO.
This still needs a bit of finessing on the other end (eg. how do we display these expired programmes?) but gives us the capability to launch them.
Nothing changes when we merge this, but we'd eventually want to stop using the "expired programme hack" we're currently using to hide BBO from the list in favour of using this.
=> Show all programmes

composer.json, composer.lock, lib/ContentHelpers.php
This adds a tag plugin which allows editing(!) of tags and their related fields:
We can then output those fields for (existing) blogs and new "updates":
Possibly Craft will add a core feature for tag editing, but until they do, this looks good to me.
=> Add tag authors tool

lib/Images.php, lib/Updates.php
This shares the hero image dimensions with the blog trail image, so we can use different crops as necessary (potentially using them like hero images if we want to, although it makes the crops from the same single image rather than three of them).
=> Add common image sizes to blog trail thumbnail

lib/ContentHelpers.php, lib/Updates.php
This adds sibling entries (eg. prev/next) and related funding programmes to the API for Updates.
=> Enhance update listings

config/element-api.php, lib/ContentHelpers.php, lib/Updates.php
A little work in progress. Returns the full list of regions in `meta` as well as the associated regions 
Does a little juggling to get the categories in a nested structure as although the CMS handles nested behaviour nicely the element query returns a flat list so we need to re-construct the nesting.
=> Add regions to updates endpoint

config/element-api.php, lib/FundingProgrammes.php
Updates the new programmes API mainly to fix an issue with statuses between listing and detail pages (listing shows expired programmes by default).
Also split the new and old transformer code into two separate transformers, making a cleaner separation between the two and making deletion simpler.
=> New programmes api tweaks

config/element-api.php, lib/ContentHelpers.php, lib/EntryHelpers.php, lib/FundingProgrammes.php, lib/Listing.php, lib/People.php, lib/Research.php, lib/StrategicProgrammes.php, lib/Updates.php
Reworks our API endpoints to support both new and re-designed hero images for all content types.
Required some reworking of–mostly older–api endpoints to use the same `getCommonFields` method.
=> Support new hero image fields

.ebextensions/php.config
One of the BBO Excel files is 16mb which I can't upload to Craft. This boosts it to 20mb which surely ought to be enough for anyone... right?
=> Allow up to 20MB file uploads 

lib/Listing.php
Very basic change here to prevent listing pages without heroes (eg. BBO subpages) from breaking the API.
=> Don't throw an error for listing child pages without hero images

lib/Updates.php
Get the correct locale prefix and use a relative path for the prev/next blogpost links.
=> Fix update sibling links to be relative

config/general.php
This means dates will now look right:
=> Default to British English

config/element-api.php
This allows the Alias entry type to simply specify a URL to redirect to rather than an entry – useful for redirecting to pages that aren't in the CMS, or even to external pages or files.
Although the field is called `externalUrl`, it can be populated with a relative one (eg. `/funding/programmes`) as it will simply be called inside `res.redirect()`.
This relates to https://github.com/biglotteryfund/blf-alpha/issues/1573 – the list of URLs to import is ready and tested with FeedMe, we just need to import them to the live database (eg. in 2019).
=> Allow URL aliases to have an external URL as opposed to an entry

config/element-api.php
Pairs with https://github.com/biglotteryfund/blf-alpha/pull/1581
Realised that the logic for the show all parameter on the programmes endpoint was wrong. This fixes that.
=> Fixup show all parameter

composer.json, composer.lock, config/element-api.php, lib/ContentHelpers.php, lib/FundingProgrammes.php, lib/ProjectStories.php
- Adds support for a new project stories section
- Adds support for quotes in flexible content
Dependant on the following new fields being added to the CMS:
=> Add project stories endpoint and transformer

lib/Images.php, lib/Updates.php
Update hero crops, inline getStandardCrops into updates transformer.
In order to support new hero images which have a variable height depending on the size of the image we need to switch to `fill` as the resize method https://docs.imgix.com/apis/url/size/fit#fill
This crops the image to the given width but preserves the aspect ratio. As we upload hero images to avoid any actually cropping this results in hero images being output at their original aspect ratio rather than being forced to the aspect ratio defined in code. For hero images this is the behaviour we want.
I've also tested with existing images to confirm that the change doesn't affect how they output.
=> Update hero crops

lib/ContentHelpers.php, lib/FundingProgrammes.php, lib/Images.php, lib/Listing.php, lib/Research.php, lib/StrategicProgrammes.php, lib/Updates.php
Add support for new hero images in trail images.
Where transformers were using a misleading `thumbnail` or `photo` property, I've standardised on `trailImage` for the new images.
=> New trail images

lib/Listing.php
Use small source image for trail image crops on listings. Especially for new style hero images this results in a much better crop across the board and avoids us needing to create custom trail images.
=> Use small source image for trail image crops on listings

composer.json, composer.lock, config/cp-js.php, web/resources/js/analytics.js, web/resources/js/analytics.test.js
This is a little out of curiosity but I think it'll be useful for us to see how the CMS is being used.
This uses @davidrapson's suggesting about the admin panel JS plugin to load in a per-environment config. It's a little funky compared to Google's copy-and-paste tracker as it's JS-only (so has to manually load what would normally be a separate `<script>` tag), but the file it's loading is meant to be `async` anyway so it works well (have tested locally).
=> Add Google Analytics

lib/Homepage.php
This tweaks the homepage single to have a matrix field like this:
This allows us to construct a list of "featured links" for the homepage.
I've already added the fields to the live CMS, and once this is out we can safely delete the (now unused) hero image field that's already there.
Pairs with https://github.com/biglotteryfund/blf-alpha/pull/1734
=> Modify homepage endpoint to return selection of featured links

lib/Homepage.php
Currently we are making two separate API calls for the homepage: one for the featured links, another for the latest news. It makes sense to combine these.
=> Add promoted updates to homepage api endpoint

config/project.yaml
Adds in the full Redactor settings so we're not limited solely to this:
(the Insights page I'm currently working on needs to have some inline links to files which I can't easily add here unless I hard-link to their URL, which isn't ideal).
=> Update Research/Insights to allow Redactor to use all toolbar elements

lib/Images.php
Prevents an issue where a linked entry (in this case, a strategic programme without a trail image) becomes unpreviewable because we're assuming a `trailPhoto` is there, when that field doesn't exist for Strategics (should it?).
=> Fix a few instances where we assume an image field exists

config/element-api.php, config/project.yaml, lib/FundingProgrammeChild.php, lib/FundingProgrammes.php
This is due to a request by the EYP team who need to create a sub-page within that programme. 
It's fairly straightforward: programme child pages can be a new entry type, "Content Page", which is just plain-old Flexible Content.
If this is adopted we could move the existing BBO subpages into this structure (although currently they *also* have child pages, so we'd need to either flatten them or adapt this PR to allow arbitrary nesting rather than just 1 level).
=> Allow funding programme pages to have child pages

config/element-api.php, config/project.yaml, lib/ContentHelpers.php, lib/FundingProgrammes.php
A few things here:
- adds a way to request a specific number of "latest" programmes for the funding landing page (rather than fetching them all and then filtering to a specific 3)
- limits the fields that are returned for listing lookups versus single pages (eg. hero lookups were especially slow)
|                               | Load time (ms) | Size (KB) |
|-------------------------------|----------------|-----------|
| Programme list (before)       | 3000           | 313kb     |
| Programme list (after)        | 1500           | 53kb      |
Things that are still slow: the listing of all programmes. Doesn't help that each time we fetch this list we fetch it a second time (for Welsh) and merge them in. Not sure how we can fix this though.
=> Improve performance of funding programmes endpoint

config/element-api.php, config/project.yaml, lib/Research.php, lib/ResearchDocument.php
This adds a new section for Insights Documents:
It allows us to upload a bunch of older research documents and then filter them on the frontend, a little like the Press Releases section.
=> Add support for research documents as well as pages

config/project.yaml, lib/ContentHelpers.php, lib/Listing.php
This adds Flexible Content fields to Listing page types (currently just for Funding Guidance section), as well as adding Title fields to each Flexible Content block type, so we can recreate the current "segment" layouts. 
It also adds "grid blocks" as a new component, eg. for this type of layout:
Pairs with https://github.com/biglotteryfund/blf-alpha/pull/1835
=> Add flexible content support to (some) listing pages

config/project.yaml
Fixes https://github.com/biglotteryfund/blf-alpha/issues/1642
Tested locally and this prevents the issue where a draft press release overwrites a draft (or even live) version in the other language.
I applied "Manage blocks on a per-site basis" to every Matrix field we have that didn't already have this checked (about half of them). Not 100% sure this is what we want but it seemed safer than risking overwriting content with the wrong language which has already bitten us in production (including yesterday!).
=> Localise all Matrix field blocks on a per-site basis

config/project.yaml, lib/Research.php, lib/ResearchDocument.php, lib/Updates.php
Video embeds were being stripped out of the content outro field for single/listing pages, so this allows them. Also adds flexible content to the Strategic Investments in England page, in case we need it there too.
=> Allow iframe embeds in Outros and add flex content to a specific single page

config/project.yaml, lib/ContentHelpers.php
Grid blocks were meant to have introductions but I think I lost them during merge hell.
Unfortunately my efforts to ship this yesterday (directly on `master` 🙈) failed due to project config sync errors when deployed to TEST – this seems to be another variation of the issues deploying anything that changes a SuperTable field.
I suspect we may need to spin up a new CMS instance with a new database and do a bunch of upgrades at once (possibly enabling admin changes on that environment, temporarily) so we can get past this – later SuperTable/Craft versions seem to have improved this side of things.
=> Add an introduction field for gridblocks

config/element-api.php
Embarrassingly, the way I'd structured this code meant that any search query was using the existence of the query (eg. `true`) as the search term, rather than whatever the query actually was. This change restores balance to the universe.
=> Fix Insight Document search

config/element-api.php, config/project.yaml
Some new merch items can only be ordered via contacting us directly. This pairs with [this frontend change](https://github.com/biglotteryfund/blf-alpha/pull/1993) and adds this field:
=> Add a field to merch items to mark them as only possible to order directly

config/project.yaml
Thought we'd found all of these but Nic/Sharon uncovered an issue with a Welsh page gaining a new English block because of this bug. Tweaks the last remaining Matrix blocks to always manage blocks per-site.
=> Fix issue with Insight blocks not being managed per-site

config/project.yaml
This is required for BBO subpages so we can make this layout:
=> Allow BBO pages to use Flexible Content

config/element-api.php, config/project.yaml
The insight documents section doesn't have a distinct URI for each item, but they were generating an invalid one which ended up in our sitemap and being crawled by bots. This adds a custom URI for them which is now handled here: https://github.com/biglotteryfund/blf-alpha/pull/2155
=> Add distinct URIs for Insight Documents and allow querying by them

config/project.yaml
Just had a call from someone who put their press release content in the "Contacts" field instead of "Content", which saved successfully, but showed a 404 on production. Turns out the flexible content field wasn't required(!) for press releases. Fixed it!
=> Ensure press releases require some content

config/project.yaml, lib/Listing.php
This is for the 25th Fund page – allows adding a set of related entries (plus a heading) to a listing page.
I initially wanted this to be a field within Flexible Content but we'll need to update SuperTable (and therefore Craft) to the latest version and this doesn't feel feasible with our current workload, so this is a bit of a manual fix for now (eg. this field is only available on listing pages, not all pages).
=> Add concept of related content to listing pages

config/element-api.php, config/project.yaml, lib/ContentHelpers.php, lib/Listing.php, lib/ProjectStories.php, lib/Updates.php, modules/control-panel/Module.php
Re-do of https://github.com/biglotteryfund/craft-dev/pull/189 after the upgrade shenanigans
Looks like this:
I had some weirdness locally after creating this where certain fields got wiped out but I think this is down to my dev environment being a bit weird. That said I want to be quite cautious launching this so will be careful with backups etc.
Pairs with https://github.com/biglotteryfund/blf-alpha/pull/2383
=> Add related content to Flexible Content matrix field

composer.json, composer.lock, config/project.yaml
This plugin doesn't work anymore with the new Craft preview/draft model (and I've removed the logic from the website) so we can disable it. Will also add a deprecation notice on the plugin page to explain it won't work in newer Craft versions.
=> Disable now-redundant preview button plugin

config/general.php, config/project.yaml, lib/Listing.php
This is quite a meaty bit of work, pairing with a frontend change. 
The idea is a bit of a do-over on how CMS content should work, generally. The goal here was to create a new section which **only** uses flexible content, supports child pages to arbitrary levels, and allows customisation of how those children are displayed on the parent page.
The goal is for the new/revamped Funding section to work under this structure. Mocked up locally like this:
There's a dropdown at the end of the Entry editor which allows customising how child pages appear:
=> Add funding section

config/general.php
A day is a bit short for a preview link to stop working, so let's make it a week.
This may or may not affect other token links like password resets / account activations – a week is probably just-about okay for these, but no-expiry would probably be too much.
=> Give preview links a lifespan of a week, not a day

config/project.yaml, lib/ContentHelpers.php, lib/Listing.php
Adds two new flexible content block types:
When paired with the new frontend template changes, this means that users can add these blocks to control the positioning of these elements rather than rely on hard-coded and slightly opaque implicit template calls, eg. having the site auto-append TOCs after the first element or child pages after the last one etc.
Tradeoff is the potential for silly/accidental content choices like duplicate TOCs/child page lists, or positioning a TOC at the end of the page etc, but we can potentially catch these and display warnings when in preview mode (perhaps a wider piece of work generally).
=> Add Flexible Content Next features

config/element-api.php, lib/FundingProgrammes.php
Including thumbnails/heroes for programme pages was spiking CPU for the CMS API – removing them when rendering the `/funding/programmes/all` page speeds up the CMS response and hopefully reduces the chance of a 504 timeout at the website end. We don't use the images on the `/all` list so it's safe to remove them here.
=> Don't fetch programme images for /all endpoint

lib/ContentHelpers.php, lib/EntryHelpers.php, lib/FundingProgrammes.php
We've had a question about [this programme page](https://www.tnlcommunityfund.org.uk/funding/programmes/coastal-communities-fund) which has a Welsh translation but doesn't offer a "Cymraeg" link (and vice-versa). 
The reason is that the API returns: `"availableLanguages": ["en"]` because the entry is expired (eg. the funding programme has closed). I've changed the code now to optionally allow an entry to be expired when checking for translations.
Currently we use expiry dates weirdly for funding programmes – eg. the content is still visible, we just use that date to determine when it closed. We should probably look at just adding a "Funding close date" field to these entries and doing it there instead, and allow expiry dates to do what they do everywhere else (eg. disable the content) to …
=> Optionally allow expired entries to be included when checking for translations

config/element-api.php, config/project.yaml, lib/ContentHelpers.php, lib/Research.php
Allow Insights pages to have children. Pairs with https://github.com/biglotteryfund/blf-alpha/pull/2914
The biggest change here is converting the section from a Channel to a Structure. This doesn't seem to have broken anything, I guess you risk losing data when going the other way (eg. structural data around ordering/ancestors etc) but this should be safer?
Otherwise this follows the same pattern as the other sections we've given child pages to.
=> Add insight child pages

config/project.yaml, lib/Listing.php
This is to make it possible to add a T&Cs page as a child of [this page](https://www.tnlcommunityfund.org.uk/funding/managing-your-grant/over-10k), but without it appearing here: 
The change is to add this field:
If this field exists and is `true` then the page will be excluded from the list of `children` in API calls. Otherwise the page will be visible.
Currently only added to the new Funding section which is the first proper place making use of the new `flexibleContentNext` which handles these child page displays.
=> Add a field to exclude children from being listed on their parent page

config/project.yaml, lib/ContentHelpers.php
Adds support for a new flexible content block type called Fact River:
Pairs with https://github.com/biglotteryfund/blf-alpha/pull/2927
=> Add a Fact River flexible content block type

config/project.yaml, lib/ContentHelpers.php, lib/FundingProgrammes.php, lib/Images.php, lib/Listing.php, lib/ProjectStories.php, lib/Research.php, lib/StrategicProgrammes.php, lib/Updates.php
This removes the old `hero` and `heroCaption` fields and replaces the references to `heroNew` back to just `hero`. Also does something similar with `trailImageNew` and `thumbnailNew`, and removing `photo` and `path` (marked for removal for ages!). Also removed some completely unused fields (as flagged by the Inventory plugin).
Pairs quite heavily with [the corresponding frontend change](https://github.com/biglotteryfund/blf-alpha/pull/2954) which will need to go out at the same time in order to avoid breaking things.
=> Remove old heroes

config/element-api.php
Child programme pages were appearing in the search dropdown, and the default sort order changed when we made this section a structure, so fixing it back to how it should be.
=> Fix Insight Docs

config/element-api.php, config/project.yaml, lib/StrategicProgrammes.php
This has a few moving bits but is basically a better solution to all of the new content being published under [A Better Start](https://www.tnlcommunityfund.org.uk/funding/strategic-investments/a-better-start#section-2). 
It does two things:
1. Adds a new section called "Publications", which is basically arbitrary (flexible) content, associated with one (or more) funding/strategic programmes. This content can be tagged (with authors as well as content tags), a bit like blogposts, or can just consist of a single document/file. There's an API endpoint to fetch this content (grouped by the first programme the Publication is tagged with), and a second one to fetch all the content tags for a given programme (eg. to build a tag cloud).
2. Adds a new field to Strategic Programmes called "Related …
=> Add new Publications section for A Better Start

lib/ContentHelpers.php
Updated default null to be empty array to work on PHP 7.2+ as this version added an incompatible change which cause null to no longer be considered a countable. 
Incompatible changes can be found here: https://www.php.net/manual/en/migration72.incompatible.php
=> Fix for PHP 7.2+ countable

config/project.yaml
A CMS user reported an issue where a page with this field couldn't be saved as it was required. Technically the field wasn't required, but its sub-fields (it's a Super Table field) _were_ required.
The culprit was this setting: 
It meant that there was a fixed display of 1 row for every section with this field. I've switched it off and now it's optional again.
=> Allow Strategic Programme Related Content to be blank

composer.json, composer.lock, config/project.yaml
This makes all of the Composer module updates in one PR (rather than deploy each dependabot change at a time) and also updates Craft to the newest version.
We were getting a deprecation warning too due to URI syntax for the new Publications section, so fixed that too.
=> Upgrade deps and fix deprecations

config/project.yaml, lib/ContentHelpers.php
Adds a new field to all Flexible Content block types:
This can then be rendered in the templates to override the (longer) block title displayed alongside its content. 
I noticed that the "Related Content" block type I added last year didn't include a `flexTitle` field (it had the same concept, `heading`), so I renamed that field and added the new `tocTitle` one too for good measure.
While I was here I also experimented with adding blank blocks of each type when in preview mode. A few (the ones that load images) rendered 500 errors when previewing, so I tweaked the logic for them to guard for missing fields better.
Also refactored the flex logic a little by outputting common fields once rather than populating them for each block type.
Pairs with …
=> Add Table of Contents title field and improve Flexible Content logic

config/project.yaml
Removed the theme colour field that was used in a few sections. Didn't appear to be referenced anywhere in the web code and so was safely removed and checked by loading the sections on the website against the live version.
=> Removed redundant 'themecolour' field.

config/project.yaml
Bit of clean up from https://github.com/biglotteryfund/craft-dev/pull/238
Spotted in the Inventory admin that `homepageHeroImages` was unused and can be removed now.
=> Deleted unused homepageHeroImages field

config/project.yaml
Adds a new section for these Insights sub-pages.
URL structure is a bit gnarly:
Has to do this though to force the URL and allow parent/child slugs etc.
=> Add new section for Covid-19 insights

config/element-api.php, lib/ContentHelpers.php, lib/EntryHelpers.php, lib/FundingProgrammes.php, lib/Listing.php, lib/People.php, lib/ProjectStories.php, lib/Research.php, lib/ResearchDocument.php, lib/StrategicProgrammes.php, lib/Updates.php
Removed all instances of getDraftorVersionEntry. The list is no longer created and so $status is directly pulled from $entry->status.
Therefore the getDraftorVersionEntry function has been removed as it is no longer being used.
=> Removed all instances of getDraftorVersionEntry

lib/Updates.php
This is to help build a new Latest blogposts widget – we need square thumbnails.
=> Add a square thumbnail for blogposts

config/project.yaml, lib/ContentHelpers.php
Pairs with https://github.com/biglotteryfund/blf-alpha/pull/3291 – adds a new block type to Flexible Content:
(open to a better name than "Automatic Content List" but struggling to work out a better way to differentiate it from "related content" etc – needs to be clear it's not pickable!)
Currently allows three choices:
Not sure if there's much call for the other 2 besides blogpost but worth having as an option. I can see a future where we'd want to add a filter here or something (eg. "only show Scotland funding programmes" or "only show blogposts tagged X") but not sure how to even approach this...
=> Add new Flexible Content block for automaticContentList

config/element-api.php, config/project.yaml, lib/FundingProgrammes.php
This pairs with [the frontend changes here](https://github.com/biglotteryfund/blf-alpha/pull/3310) and adds two things:
- A global set for C19 statuses by country:
(thought this was a nice opportunity to try these out for something that we'd otherwise have to hardcode in the app, and will likely change/evolve frequently)
- A new 'trail text' field for funding programmes:
(This is limited to 300 characters to avoid the possibility of anyone dumping tons of text in at a future date 😎)
=> Add Covid-19 funding info

config/redactor/Full.json, config/redactor/plugins/linkButton.js, web/resources/css/cp.css
Adds some new formatting styles to help control the [impending new design for the Contact page](https://github.com/biglotteryfund/blf-alpha/issues/2500):
(still awaiting a fax icon!)
Has some corresponding frontend changes to style these classes.
=> Add CMS formatting styles

config/element-api.php, config/project.yaml, lib/ContentHelpers.php, lib/Listing.php
Add a new flex content block to allow migration of the [Our People](https://github.com/biglotteryfund/blf-alpha/issues/3366) section.
This means that we can deprecate the old structure and move these pages directly into the About section.
There's also a change in here to enable showing "sibling" pages in a sidebar, eg:
The logic was already there for this but it didn't work correctly for top-level pages which didn't have parents. The change here makes this work for parentless pages.
Pairs with https://github.com/biglotteryfund/blf-alpha/pull/3458
=> Add new Person type to Flexible Content

config/element-api.php
Spotted this earlier:
1. Visit the Publication Search and enter [a query like "baby"](https://www.tnlcommunityfund.org.uk/funding/publications/a-better-start?q=baby)
2. Note the number of results – 17
3. [Re-order the search results by date](https://www.tnlcommunityfund.org.uk/funding/publications/a-better-start?q=baby&sort=newest) – now there are 49 results!?
This is due to a silly error in the search code which only uses the `q=baby` parameter when the `sort` type is `score` or not specified. This change separates out that logic from the search criteria code.
(the same bug is present on [the Insights Documents search](https://www.tnlcommunityfund.org.uk/insights/documents?q=HeadStart), which the Publication Search code is based on, so I've fixed it there too).
=> Fix document query search bug

config/project.yaml, lib/FundingProgrammes.php, lib/Listing.php
Adds a new field like this:
Currently supported for the Funding Programmes and Funding sections. Pairs with this frontend change: https://github.com/biglotteryfund/blf-alpha/pull/3584
=> Add new Notification Banner field to Funding and Funding Programmes sections

config/element-api.php, config/project.yaml, lib/Research.php
Quick change by request of the Knowledge & Learning team – they want to be able to create flexible content pages in their Insights section, rather than just the existing type which is fairly templated (eg. [like this](https://www.tnlcommunityfund.org.uk/insights/building-resilience)). 
We already use this `contentPage` pattern in a few other sections so this was simple enough to add here.
Pairs with https://github.com/biglotteryfund/blf-alpha/pull/3608
=> Allow Insights section to have a new 'Content Page' entry type

config/project/entryTypes/grantmakingPractice--34dc3ee3-72ff-4906-a9df-4b2b94c9ad15.yaml
Fix for a problem when users updated the title in welsh on the grantmaking practice section - it would update the title on the english version of the page as well and vice versa
=> Title translates for each site 

craft
AWS build fails after updates due to index issue. This may resolve the problem.
=> Potential fix for AWS build failure.

config/redactor/Basics.json, config/redactor/Full.json, config/redactor/Minimal.json
removed "italics" option from all button lists in the redactor json files. tested and doing so removes the button from the editors.
=> Removing italics button as per web-87

lib/Images.php, tests/ImagesTest.php
Image cropping was previously using just entropy by default, updated to use faces then edge detection to improve smaller size images.
=> WEB-97 Updated default image crop
